### ISSUE TITLE
Take in care SemVer

### ISSUE THREAD

**Issue by McGiverGim** [stpettersens/gulp-debian#19]
Hi! This is only a suggestion. The SemVer in `npm` marks the versions as `X.Y.Z` being Z a pach to the version that does not modify the behaviour of the library. In `package.json` a "~x.y.z" says that the Z can be changed and is not a problem because it is totally compatible.

The latest version 0.1.8 was not compatible with earlier versions (0.1.7 for example) and it broke all the builds that use this library because the new parameter is mandatory.

Is not a problem, I will change where I'm using it to add the new parameter (I think is important to have the copyright) but being a public library I think that the SemVer must be accomplished ;)

Thanks again for your work!!

**Comment by stpettersens** [comment]
The new parameter shouldn't be mandatory in my opinion. I will look into
this on the weekend. This is an oversight on my part.

I agree with you on the breaking changes. SemVer will be adopted from 0.2.0.

**Comment by lucomsky** [comment]
@stpettersens, `copyright` parameter is mandatory due to [Debian policy](https://www.debian.org/doc/debian-policy/#copyright-information).
So try to check package without `copyright` by `lintian -c package.deb`

**Comment by stpettersens** [comment]
I want to allow some flexibility. If you want to make a fork that is more
stringent to Debian policy go ahead.

 IMO if the packages work without the copyright file I am going to allow
it.

Debian policy compliance was not originally a priority of this project. Its
good that you added copyright file functionality but I'd prefer to take the
approach of strongly suggest rather than mandate. That's why I'm displaying
a warning to the user but still making the parameter functionally
optional.

Thanks for your feedback.

**Comment by lucomsky** [comment]
No problem. I just mentioned it ;-)

**Comment by stpettersens** [comment]
It has been agreed to use semantic versioning as of publish of `gulp-debian@0.2.0`. This issue has can now be closed.
