### ISSUE TITLE
Changelog support

### ISSUE THREAD

**Issue by OlafRadicke** [stpettersens/gulp-debian#3]
Hi!

Do you have a idea for a implementation of a changelog support? Do you prefer a external file how is loaded from gulp-debian or better as embedded information in the Gulpfile.js? If we say external file is the best way than as yaml file or better json?

**Comment by stpettersens** [comment]
I would probably add support for both. In most cases from a file is more practical but adding support for inline in the object as an array of changes is easy enough because we can load from the same structure in either JSON or YAML. Adding YAML support in general to this plugin is not a bad idea either but I'd give priority to JSON due to its natural support in the JS ecosystem. Thanks for suggestions, @OlafRadicke!

**Comment by OlafRadicke** [comment]
Okay, here my format suggestion:

```
{
  "changelog": [
    {
      "package":"hello-weld",
      "version":"0.1.6",
      "distribution":"unstable",
      "urgency":"low",
      "change":[
        "fix bug-634",
        "fix bug-533",
        "Add new button"
      ]
    },
    {
      "package":"hello-weld",
      "version":"0.1.5",
      "distribution":"unstable",
      "urgency":"high",
      "change":[
        "security fix bug-343"
      ]
    }
  ]
}
```

**Comment by stpettersens** [comment]
Looks good to me. Want me to implement it or do you want to do it yourself? :)

**Comment by OlafRadicke** [comment]
As you like. JavaScript is not my daily business so when you do this I'm not unhappy. ;-)

**Comment by stpettersens** [comment]
Thanks, man. I'll definitely put in those suggestions.

**Comment by stpettersens** [comment]
This is now (at least initially) implemented under version 0.1.4. But with the following tweaks:

 - A date field (which takes an ISO 8601 date such as 2016-12-29T21:27:34 in either string literal or Date object format).

- An array field called change*s* rather than just change.

Example follows:

 ```
   changelog: [
      {
        version: '0.1-2',
        distribution: 'unstable',
        urgency: 'low',
        date: new Date('2016-12-24T12:40:10'),
        changes: [
          'Added another feature.',
          'Fixed feature X.'
        ]
      },
      (.... another changelog array entry)
```

Thanks.

**Comment by OlafRadicke** [comment]
Thank you for you work. The code looks clear for me.

**Comment by stpettersens** [comment]
You're welcome.

**Comment by stpettersens** [comment]
You can use an external JSON file to specify a package as of version 0.1.5.
Just put a string with the JSON filename where you would otherwise put the Object.

```js
'use strict'

const gulp = require('gulp')
const deb = require('gulp-debian')

gulp.task('deb-json', function () {
  return gulp.src(['foo', 'bar'])
  .pipe(deb('mypackage_0.1-0_i386.json'))
})
```

Thanks.

**Comment by OlafRadicke** [comment]
Hi,
the external JSON file is a great idea! The implementation is clear and understandable. Yah, I like it. Is the documentation in the readme file up to date?

Best regards

Olaf

**Comment by stpettersens** [comment]
No. It needs updated.
